# Generated by Django 4.2.1 on 2023-05-10 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'default_related_name': 'room', 'ordering': ['-number'], 'verbose_name': 'Room'},
        ),
    ]
