# Generated by Django 4.2.1 on 2023-05-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_room_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='cost',
            field=models.FloatField(default=0, verbose_name='Price for room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='count',
            field=models.PositiveIntegerField(verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Number of room'),
        ),
    ]
